---
apiVersion: v1
kind: Service
metadata:
    name: foodgram-db
    labels:
        name: postgres-service
        app: foodgram
spec:
    ports:
        - port: 5432
          targetPort: 5432
    selector:
        name: foodgram-postgres-pod
        app: foodgram
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: foodgram-postgres-deploy
    labels:
        name: foodgram-postgres-deploy
        app: foodgram
spec:
    replicas: 1
    selector:
        matchLabels:
          name: foodgram-postgres-pod
          app: foodgram
    template:
      metadata:
          name: foodgram-postgres-pod
          labels:
              name: foodgram-postgres-pod
              app: foodgram
      spec:
          containers:
              - name: foodgram-postgres
                image: postgres
                ports:
                    - containerPort: 5432
                env:
                    - name: POSTGRES_USER
                      value: "postgres"
                    - name: POSTGRES_PASSWORD
                      value: "postgres"
                    - name: POSTGRES_HOST_AUTH_METHOD
                      value: trust
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
    labels:
        name: nginx-service
        app: foodgram
spec:
    ports:
        - port: 80
          targetPort: 80
    selector:
        name: nginx-pod
        app: foodgram
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deploy
    labels:
        name: nginx-deploy
        app: foodgram
spec:
    replicas: 1
    selector:
        matchLabels:
          name: nginx-pod
          app: demo-voting-app
    template:
      metadata:
          name: nginx-pod
          labels:
              name: nginx-pod
              app: foodgram
      spec:
          containers:
              - name: nginx
                image: nginx
                ports:
                    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: foodgram-frontend-service
  labels:
    name: foodgram-frontend-service
    app: foodgram
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
     name: foodgram-frontend-pod
     app: foodgram
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: foodgram-frontend-deploy
    labels:
        name: foodgram-frontend-deploy
        app: foodgram
spec:
    replicas: 1
    selector:
        matchLabels:
          name: foodgram-frontend-pod
          app: foodgram 
    template:
      metadata:
          name: foodgram-frontend-pod
          labels:
              name: foodgram-frontend-pod
              app: foodgram
      spec:
          containers:
              - name: foodgram-frontend
                image: zaariel91/foodgram_frontend
                ports:
                    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: foodgram-backend-service
  labels:
    name: foodgram-backend-service
    app: foodgram
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
     name: foodgram-backend-pod
     app: foodgram
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: foodgram-backend-deploy
    labels:
        name: foodgram-backend-deploy
        app: foodgram
spec:
    replicas: 1
    selector:
        matchLabels:
          name: foodgram-backend-pod
          app: foodgram 
    template:
      metadata:
          name: foodgram-backend-pod
          labels:
              name: foodgram-backend-pod
              app: foodgram
      spec:
          containers:
              - name: foodgram-backend
                image: zaariel91/foodgram_backend
                ports:
                    - containerPort: 80
---
